dist: trusty
os: linux
language: node_js
node_js: 15.8
install: npm i

jobs:
  include:
    - name: Lint
      script: npm run lint

    - stage: Test
      name: Unit tests
      before_script: ganache-cli > /dev/null &
      script: truffle test

    - name: Coverage
      script:
        - truffle run coverage
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
